# Generated by Django 5.1 on 2026-08-22 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('tipo', models.CharField(choices=[('cable', 'Cable'), ('inalambrico', 'Inalambrico'), ('gaming', 'Gaming')], max_length=20, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('precio', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('tipo', models.CharField(choices=[('optico', 'Optico'), ('inalambrico', 'Inalambrico'), ('gaming', 'Gaming')], max_length=20, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('precio', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mousepad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('tipo', models.CharField(choices=[('tela', 'Tela'), ('vidrio', 'Vidrio'), ('gaming', 'Gaming')], max_length=20, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('precio', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teclado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('tipo', models.CharField(choices=[('membrana', 'Membrana'), ('mecanico', 'Mecanico'), ('semimecanico', 'SemiMecanico')], max_length=20, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('precio', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('imagen', models.ImageField(upload_to='productos/')),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
    ]
