# Generated by Django 4.2 on 2024-08-14 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_actividad_aprendiz_experiencia_mentor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teclado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('membrana', 'Membrana'), ('mecanico', 'Mecanico'), ('semimecanico', 'SemiMecanico')], max_length=40)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('precio', models.IntegerField(blank=True, max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Experiencia',
        ),
    ]
