# Generated by Django 5.1 on 2024-08-16 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auricular_delete_mentor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mousepad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('tipo', models.CharField(choices=[('tela', 'Tela'), ('vidrio', 'Vidrio'), ('gaming', 'Gaming')], max_length=20, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('precio', models.IntegerField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Actividad',
        ),
    ]
