# Generated by Django 4.2 on 2024-08-14 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0003_teclado_delete_experiencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='teclado',
            name='tipo',
            field=models.CharField(choices=[('membrana', 'Membrana'), ('mecanico', 'Mecanico'), ('semimecanico', 'SemiMecanico')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teclado',
            name='nombre',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='teclado',
            name='precio',
            field=models.IntegerField(blank=True),
        ),
    ]
