# Generated by Django 5.1 on 2024-08-14 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0004_teclado_tipo_alter_teclado_nombre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('tipo', models.CharField(choices=[('optico', 'Optico'), ('inalambrico', 'Inalambrico'), ('gaming', 'Gaming')], max_length=20, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('precio', models.IntegerField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Aprendiz',
        ),
        migrations.DeleteModel(
            name='NivelDeAprendizaje',
        ),
    ]
