# Generated by Django 5.1 on 2024-08-15 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0005_mouse_delete_aprendiz_delete_niveldeaprendizaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('tipo', models.CharField(choices=[('cable', 'Cable'), ('inalambrico', 'Inalambrico'), ('gaming', 'Gaming')], max_length=20, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('precio', models.IntegerField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Mentor',
        ),
    ]
